version: 2
updates:
- package-ecosystem: cargo
  directory: "/"
  schedule:
    interval: daily
  cooldown:
    default: 3
    default-days: 7
  open-pull-requests-limit: 10
  reviewers:
  - alexander-akhmetov
  assignees:
  - alexander-akhmetov
