[package]
name = "apple1"
version = "0.1.0"
authors = ["Alexander Akhmetov <me@aleks.sh>"]
edition = "2018"

[dependencies]
log = "0.4"
env_logger = "0.6.1"
clap = "2.33.0"
ncurses = "5.99.0"
mos6502 = {git = "https://github.com/alexander-akhmetov/mos6502/", tag = "0.1.0"}
