name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

permissions: {}

jobs:
  build:

    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
    - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1
      with:
        persist-credentials: false
    - name: Build
      run: cargo build --verbose --features binary
    - name: Run tests
      run: cargo test --verbose --features binary
